export const SPOTS_BY_COUNTRY: Record<string, readonly string[]> = {
  // ── ASIA ─────────────────────────────────────────────────
  'Sri Lanka': [
    // East coast – Arugam Bay area
    'Arugam Bay (Baby Point)',
    'Arugam Bay (Main Point)',
    'Crocodile Rock',
    'Elephant Rock',
    'Lighthouse (A-Bay)',
    'Okanda',
    'Panama (Rights)',
    'Peanut Farm',
    'Pottuvil Lagoon Mouth',
    'Pottuvil Point',
    'The Wedge',
    'Whiskey Point',
    // South coast
    'Ahangama',
    'Dalawella',
    "Devil's Rock / The Rock (Ahangama)",
    'Dickwella',
    'Galle (Reefs)',
    'Gas Station',
    'Hiriketiya',
    'Kabalana',
    'Marshmallow',
    'Matara',
    'Midigama',
    'Midigama (Lazy Left)',
    'Midigama (Lazy Right)',
    'Mirissa',
    'Talalla',
    'Unawatuna',
    'Weligama Bay',
    // Southwest coast
    'Bentota',
    'Hikkaduwa',
    'Hikkaduwa (Main Reef)',
    'Hikkaduwa (North Jetty)',
    'Hikkaduwa (Rivermouth)',
    'Mount Lavinia',
    // East / North
    'Arugam Bay (Mudu)',
    'Nilaveli',
  ],
  'Indonesia': [
    // Bali – Bukit Peninsula
    'Balangan',
    'Bingin',
    'Dreamland',
    'Green Bowl',
    'Impossibles',
    'Nyang Nyang',
    'Padang Padang',
    'Suluban / Blue Point',
    'Uluwatu',
    // Bali – South
    'Airport Lefts',
    'Airport Rights',
    'Halfway',
    'Kuta Beach',
    'Kuta Reef',
    'Nusa Dua',
    'Sanur Reef',
    'Serangan',
    // Bali – Canggu / West
    'Canggu (Batu Bolong)',
    'Canggu (Berawa)',
    'Canggu (Echo Beach)',
    'Canggu (Old Man\'s)',
    'Pererenan',
    'Seseh',
    'Tanah Lot',
    // Bali – East
    'Hyatt Reef',
    'Keramas',
    'Ketewel',
    // Bali – West & North
    'Balian',
    'Cekik (Secret Spot)',
    'Medewi',
    // Nusa Islands
    'Ceningan (The Cliff)',
    'Lembongan (Lacerations)',
    'Lembongan (Playgrounds)',
    'Lembongan (Razors)',
    'Lembongan (Shipwrecks)',
    'Nusa Penida',
    // Lombok
    'Desert Point',
    'Ekas',
    'Gerupuk (Don Don)',
    'Gerupuk (Inside)',
    'Gerupuk (Outside)',
    'Kuta Lombok',
    'Mawi',
    'Selong Belanak',
    'Senggigi',
    'Tanjung Aan',
    // Sumbawa
    'Lakey Peak',
    'Lakey Pipe',
    'Periscopes',
    'Scar Reef',
    'Supersuck (Sumbawa)',
    'Yo-Yo\'s',
    // Sumba
    'Nihiwatu (God\'s Left)',
    'Tarimbang',
    // Java
    'Batu Karas',
    'Cimaja',
    'G-Land (Grajagan)',
    'Ombak Tujuh (Seven Waves)',
    'Pacitan (various)',
    'Panaitan (One Palm Point)',
    // Sumatra
    'Krui (Mandiri)',
    'Krui (The Peak)',
    'Krui (Way Jambu)',
    'Nias (Lagundri Bay / Sorake)',
    'Nias (The Point)',
    'Tanjung Setia (Krui)',
    // Mentawais
    'Mentawais (Bankvaults)',
    'Mentawais (Beng Bengs)',
    'Mentawais (E-Bay)',
    'Mentawais (Greenbush)',
    'Mentawais (HT\'s)',
    'Mentawais (Kandui Left)',
    'Mentawais (Lance\'s Left)',
    'Mentawais (Lance\'s Right)',
    'Mentawais (Macaronis)',
    'Mentawais (Nipussi)',
    'Mentawais (Pitstops)',
    'Mentawais (Rifles)',
    'Mentawais (Telescopes)',
    'Mentawais (Thunders)',
    // Aceh
    'Aceh (Lhoknga)',
  ],
  'Japan': [
    // Chiba
    'Chiba (Maruki)',
    'Ichinomiya (Shidashita)',
    'Katsuura',
    'Onjuku',
    'Taito Beach',
    // Shonan
    'Enoshima',
    'Shonan (Chigasaki)',
    'Shonan (Fujisawa)',
    'Shonan (Kugenuma)',
    // Shikoku
    'Ikumi',
    'Kaifu (Shikoku)',
    'Nahari',
    // Miyazaki
    'Aoshima',
    'Kisakihama',
    'Kizaki-hama',
    // Islands
    'Niijima',
    'Tanegashima',
    'Yakushima',
    // Others
    'Isonoura',
    'Shirahama (Wakayama)',
  ],
  'Philippines': [
    // Siargao
    'Cloud 9',
    'Daku Reef',
    'Jacking Horse',
    'Pacifico (Siargao)',
    'Quicksilver',
    'Rock Island',
    'Stimpy\'s',
    'Tuason Point',
    // La Union
    'Monaliza Point',
    'San Juan (La Union)',
    'Urbiztondo',
    // Baler (Aurora)
    'Cemento Reef',
    'Charlie\'s Point',
    'Lindy\'s Point',
    'Sabang Beach (Baler)',
    // Catanduanes
    'Majestics (Catanduanes)',
    'Puraran',
    // Zambales
    'Crystal Beach (Zambales)',
    'San Felipe',
    'San Narciso',
    // Others
    'Bagasbas (Camarines Norte)',
    'Dahican (Mati)',
    'Lanuza (Surigao)',
    'Pagudpud',
  ],
  'Maldives': [
    // North Male Atoll
    'Chickens',
    'Cokes',
    'Honky\'s',
    'Jailbreaks',
    'Lohis',
    'Ninjas',
    'Pasta Point',
    'Sultans',
    'Tucky Joe\'s',
    // South Male Atoll
    'Guru\'s',
    'Last Stop',
    'Native',
    'Quarters',
    'Riptides',
    // Central Atolls
    'Malik\'s',
    'Twin Peaks (Meemu Atoll)',
    'Veyvah Point',
    // Outer Atolls
    'Five Islands (Laamu)',
    'Refugees',
    'Yin Yang (Laamu)',
  ],
  'Taiwan': [
    'Baishawan',
    'Dulan',
    'Jialeshuei',
    'Jinzun Harbor',
    'Nanwan',
    'Wai-Ao',
    'Zhongjiao Bay',
  ],

  // ── OCEANIA ──────────────────────────────────────────────
  'Australia': [
    // Queensland – Gold Coast
    'Burleigh Heads',
    'Currumbin Alley',
    'Duranbah',
    'Greenmount',
    'Kirra',
    'Palm Beach Reef',
    'Snapper Rocks',
    'The Spit',
    // Queensland – Sunshine Coast / North
    'Alex Headland',
    'Caloundra (Kings Beach)',
    'Mooloolaba',
    'Noosa (First Point)',
    'Noosa (Nationals)',
    'Noosa (Tea Tree)',
    'North Stradbroke Island',
    'Sunshine Beach',
    // NSW – North Coast
    'Angourie',
    'Broken Head',
    'Byron Bay (Tallows)',
    'Byron Bay (The Pass)',
    'Byron Bay (The Wreck)',
    'Coffs Harbour (Park Beach)',
    'Crescent Head',
    'Lennox Head',
    'South West Rocks',
    'Yamba',
    // NSW – Central Coast / Hunter
    'Avoca Beach',
    'Dee Why',
    'Freshwater',
    'Newcastle (Bar Beach)',
    'Newcastle (Merewether)',
    'Newcastle (Nobbys)',
    'North Narrabeen',
    // NSW – Sydney
    'Bondi',
    'Cronulla (The Point)',
    'Curl Curl',
    'Manly',
    'Maroubra',
    'Narrabeen',
    // NSW – South Coast
    'Bermagui (various)',
    'Jervis Bay (various)',
    'Merimbula',
    'Narooma (various)',
    'Ulladulla (various)',
    // Victoria – Great Ocean Road
    '13th Beach',
    'Bells Beach',
    'Gunnamatta',
    'Jan Juc',
    'Johanna',
    'Lorne',
    'Ocean Grove',
    'Phillip Island (Woolamai)',
    'Point Addis',
    'Portsea (Back Beach)',
    'Torquay (Cosy Corner)',
    'Winkipop',
    // Western Australia – Margaret River
    'Gnaraloo',
    'Gracetown',
    'Lefthanders',
    'Margaret River (Main Break)',
    'Margaret River (Surfers Point)',
    'North Point',
    'Prevelly',
    'Red Bluff',
    'The Box',
    'Yallingup',
    // Western Australia – Perth
    'Cottesloe',
    'Rottnest Island (Stark Bay)',
    'Rottnest Island (Strickland Bay)',
    'Scarborough',
    'Trigg',
    // South Australia
    'Cactus Beach',
    'Middleton',
    'Parsons Beach',
    'Pennington Bay (Kangaroo Island)',
    'Pondalowie Bay',
    'Waitpinga',
    // Tasmania
    'Clifton Beach (Tas)',
    'Eaglehawk Neck',
    'Marrawah',
    'Shipstern Bluff',
  ],
  'New Zealand': [
    // Waikato / Bay of Plenty
    'Mount Maunganui',
    'Papamoa',
    'Raglan (Indicators)',
    'Raglan (Manu Bay)',
    'Raglan (Whale Bay)',
    // Auckland
    'Bethells Beach',
    'Muriwai',
    'Piha',
    // Northland
    'Ahipara',
    'Mangawhai Heads',
    'Shipwreck Bay',
    // East Cape
    'Gisborne (Makorori)',
    'Gisborne (Wainui)',
    'Mahia',
    // Taranaki
    'Fitzroy Beach',
    'Kumara Patch',
    'Stent Road',
    // Wellington / Wairarapa
    'Castlepoint',
    'Lyall Bay',
    'Riversdale',
    // South Island
    'Kaikoura',
    'Papatowai',
    'Porpoise Bay (Curio Bay)',
    'Punakaiki',
    'St Clair (Dunedin)',
    'Sumner',
    'Tauranga Bay (Westport)',
    'Taylors Mistake',
  ],
  'Fiji': [
    'Cloudbreak',
    'Desperations',
    'Frigates',
    'King Kong Left',
    'Lighthouse (Kadavu)',
    'Namotu Lefts',
    'Natadola',
    'Restaurants',
    'Sigatoka Rivermouth',
    'Swimming Pools',
    'Tavarua Rights',
    'Wilkes Pass',
  ],
  'Tahiti / French Polynesia': [
    'Maraa',
    'Papara',
    'Papenoo',
    'Sapinus',
    'Taapuna',
    'Teahupo\'o',
    'Vairao',
  ],

  // ── AMERICAS ─────────────────────────────────────────────
  'United States': [
    // Hawaii – Oahu
    'Ala Moana Bowls',
    'Backdoor',
    'Chun\'s Reef',
    'Diamond Head',
    'Haleiwa (Alii Beach Park)',
    'Kaiser\'s',
    'Laniakea',
    'Makaha',
    'Pipeline',
    'Rocky Point',
    'Sandy Beach',
    'Sunset Beach (Oahu)',
    'Velzyland',
    'Waimea Bay',
    // Hawaii – Maui
    'Ho\'okipa',
    'Honolua Bay',
    'Lahaina Harbor',
    'Lanes (Maui)',
    'Peahi (Jaws)',
    // Hawaii – Kauai
    'Hanalei Bay',
    'Pakala Village (Infinities)',
    'Polihale',
    'Tunnels',
    // Hawaii – Big Island
    'Banyans (Big Island)',
    'Honoli\'i',
    'Pine Trees (Big Island)',
    // California – Southern
    '54th Street (Newport)',
    'Black\'s Beach',
    'Bolsa Chica',
    'C Street (Ventura)',
    'Cardiff Reef',
    'Church (San Clemente)',
    'County Line',
    'Dana Point',
    'Doheny',
    'El Porto',
    'Emma Wood',
    'Hermosa Beach',
    'Huntington Pier',
    'Imperial Beach',
    'La Jolla Shores',
    'Malibu (First Point)',
    'Malibu (Second Point)',
    'Malibu (Third Point)',
    'Manhattan Beach (El Porto)',
    'Newport Point',
    'Newport Wedge',
    'Rincon',
    'Salt Creek',
    'San Clemente Pier',
    'San Onofre',
    'Scripps',
    'Silver Strand',
    'Swami\'s',
    'T-Street (San Clemente)',
    'Topanga',
    'Tourmaline',
    'Trestles (Cottons)',
    'Trestles (Lowers)',
    'Trestles (Upper)',
    'Ventura Point',
    'Windansea',
    'Zuma',
    // California – Central
    'Jalama',
    'Marina State Beach',
    'Mitchell\'s Cove',
    'Moss Landing',
    'Pacific Grove',
    'Pismo Beach',
    'Pleasure Point',
    'Refugio',
    'Steamer Lane',
    // California – NorCal
    'Bolinas',
    'Linda Mar (Pacifica)',
    'Mavericks',
    'Ocean Beach (San Francisco)',
    'Stinson Beach',
    // East Coast
    'Asbury Park',
    'Belmar',
    'Cape Hatteras (Outer Banks)',
    'Ditch Plains',
    'Folly Beach',
    'Long Beach (NY)',
    'Manasquan Inlet',
    'Montauk',
    'Rockaway',
    'Wrightsville Beach',
    // Florida
    'Cocoa Beach',
    'Jacksonville Beach',
    'New Smyrna Beach',
    'Ponce Inlet',
    'Reef Road (Palm Beach)',
    'Sebastian Inlet',
    'St. Augustine',
    // Puerto Rico
    'Domes (Puerto Rico)',
    'Gas Chambers (Puerto Rico)',
    'Maria\'s (Puerto Rico)',
    'Rincon (Puerto Rico)',
    'Sandy Beach (Puerto Rico)',
    'Surfer\'s Beach (Aguadilla)',
    'Tres Palmas (Puerto Rico)',
    'Wilderness (Puerto Rico)',
    // Great Lakes / Texas
    'Galveston (TX)',
    'South Padre Island',
  ],
  'Canada': [
    // British Columbia
    'Jordan River',
    'Sombrio Beach',
    'Tofino (Chestermans)',
    'Tofino (Cox Bay)',
    'Tofino (Long Beach)',
    'Tofino (Wickaninnish)',
    // Nova Scotia
    'Cow Bay',
    'Lawrencetown',
    'Lawrencetown Point',
    'Martinique Beach',
  ],
  'Mexico': [
    // Baja California Sur
    'Cabo San Lucas (Monuments)',
    'Cerritos',
    'Costa Azul',
    'El Tule',
    'Nine Palms',
    'San Pedrito',
    'Shipwrecks',
    'Todos Santos',
    'Zippers',
    // Baja California
    'Isla Todos Santos (Big Wave)',
    'K-38 / Salsipuedes corridor',
    'K-55',
    'Punta Abreojos',
    'Punta San Carlos',
    'San Miguel (Ensenada)',
    'Scorpion Bay (San Juanico)',
    // Oaxaca
    'Barra de la Cruz',
    'Carrizalillo',
    'Chacahua',
    'La Punta (Puerto Escondido)',
    'Puerto Escondido (Zicatela)',
    'Salina Cruz points (various)',
    'Zipolite',
    // Nayarit / Riviera Nayarit
    'Burros',
    'La Lancha',
    'Lo de Marcos',
    'Punta de Mita',
    'San Pancho',
    'Sayulita',
    // Jalisco
    'Boca de Pascuales',
    // Colima / Michoacan / Guerrero
    'Ixtapa (Escolleras)',
    'La Saladita',
    'Manzanillo',
    'Nexpa',
    'Pascuales',
    'Petacalco',
    'Playa Linda (Ixtapa)',
    'Troncones',
  ],
  'Costa Rica': [
    // Guanacaste (North Pacific)
    'Avellanas (Little Hawaii)',
    'Junquillal',
    'Langosta',
    'Marbella',
    'Ollie\'s Point',
    'Playa Grande',
    'Playa Negra',
    'Tamarindo',
    'Witch\'s Rock',
    // Nicoya Peninsula
    'Camaronal',
    'Mal Pais',
    'Manzanillo (Nicoya)',
    'Nosara (Guiones)',
    'Ostional',
    'Playa Carmen',
    'Playa Hermosa (Santa Teresa)',
    'Samara',
    'Santa Teresa',
    // Central Pacific
    'Bejuco',
    'Boca Barranca',
    'Esterillos',
    'Jaco',
    'Playa Escondida',
    'Playa Hermosa (Central)',
    // South Pacific
    'Dominical',
    'Dominicalito',
    'Matapalo',
    'Pavones',
    'Uvita',
    // Caribbean
    'Cocles',
    'Playa Bonita',
    'Puerto Viejo',
    'Salsa Brava',
  ],
  'Nicaragua': [
    // Rivas / Tola
    'Lance\'s Left (Nicaragua)',
    'Manzanillo (Nicaragua)',
    'Panga Drops',
    'Playa Colorado',
    'Playa Santana',
    'Playgrounds (Nicaragua)',
    'Popoyo',
    // San Juan del Sur area
    'Playa Hermosa (Nicaragua)',
    'Playa Maderas',
    'Playa Marsella',
    'Playa Remanso',
    'Playa Yankee',
    'San Juan del Sur (beachbreak)',
    // North
    'Aposentillo',
    'Astillero',
    'Las Peñitas',
    'Poneloya',
  ],
  'El Salvador': [
    // La Libertad
    'Conchalio',
    'El Sunzal',
    'El Tunco',
    'El Zonte',
    'K-59 (El Salvador)',
    'La Bocana',
    'Punta Roca',
    'San Blas',
    // East
    'El Cuco',
    'Las Flores',
    'Mizata',
    'Punta Mango',
    // West
    'Los Cobanos',
  ],
  'Panama': [
    'Bocas del Toro (Bluff Beach)',
    'Bocas del Toro (Dumpers)',
    'Bocas del Toro (Paunch)',
    'Bocas del Toro (Silverbacks)',
    'Cambutal',
    'Coronado',
    'Playa Morrillo',
    'Playa Teta',
    'Playa Venao',
    'Red Frog Beach',
    'Santa Catalina',
  ],
  'Peru': [
    // North
    'Cabo Blanco',
    'Chicama',
    'Huanchaco',
    'Lobitos',
    'Máncora',
    'Pacasmayo',
    'Órganos',
    // Lima Area
    'Caballeros',
    'Cerro Azul',
    'Kon Tiki',
    'La Herradura',
    'Makaha (Peru)',
    'Pico Alto',
    'Playa Waikiki (Lima)',
    'Punta Hermosa',
    'Punta Rocas',
    'San Bartolo',
    'Señoritas',
    // South
    'Arica (Peru side)',
  ],
  'Chile': [
    // Norte Grande
    'Arica (El Buey)',
    'Arica (El Gringo)',
    'Arica (La Isla)',
    'Iquique (Huayquique)',
    'Iquique (Punta Cavancha)',
    // Central
    'Con-Con (Playa Negra)',
    'Constitución',
    'Matanzas',
    'Pichilemu (Infiernillo)',
    'Pichilemu (La Puntilla)',
    'Pichilemu (Punta de Lobos)',
    'Renaca',
    'Reñaca',
    'Ritoque',
    'Topocalma',
    'Viña del Mar',
    // South
    'Buchupureo',
    'Cobquecura',
    'Lebu',
    'Pelluhue',
    'Puertecillo',
  ],
  'Ecuador': [
    'Ayampe',
    'Canoa',
    'Engabao',
    'Galápagos (Tortuga Bay)',
    'Mompiche',
    'Montañita',
    'Olón',
    'Playa de los Frailes',
    'Same',
    'San Mateo',
    'Santa Marianita',
  ],
  'Brazil': [
    // Rio de Janeiro
    'Arpoador',
    'Barra da Tijuca',
    'Buzios (various)',
    'Copacabana (corners)',
    'Grumari',
    'Prainha (Rio)',
    'Saquarema (Itauna)',
    // Santa Catarina
    'Ferrugem',
    'Florianopolis (Barra da Lagoa)',
    'Florianopolis (Campeche)',
    'Florianopolis (Joaquina)',
    'Florianopolis (Praia Mole)',
    'Florianopolis (Santinho)',
    'Garopaba',
    'Guarda do Embau',
    'Imbituba',
    'Imbituba (Praia da Vila)',
    'Praia Brava (Itajai)',
    'Praia do Rosa',
    'Torres',
    // São Paulo
    'Camburi',
    'Guaruja (Praia do Tombo)',
    'Itamambuca',
    'Maresias',
    'Santos (various)',
    'Ubatuba (Praia Grande)',
    'Ubatuba (Praia Vermelha)',
    // Northeast
    'Fernando de Noronha (Boldró)',
    'Fernando de Noronha (Cacimba do Padre)',
    'Itacare',
    'Maracaipe',
    'Porto de Galinhas',
    'Praia da Pipa',
    'Stella Maris (Salvador)',
    'São Conrado (Rio)',
    // South
    'Farol de Santa Marta',
    'Torres (RS)',
  ],

  // ── EUROPE ───────────────────────────────────────────────
  'Portugal': [
    // Peniche area
    'Almagreira',
    'Baleal',
    'Cantinho da Baía',
    'Consolacao',
    'Lagide',
    'Molho Leste',
    'Supertubos (Peniche)',
    // Nazaré
    'Nazare (Praia da Vila)',
    'Nazare (Praia do Norte)',
    'Sao Martinho do Porto',
    // Ericeira (World Surfing Reserve)
    'Ericeira (Cave)',
    'Ericeira (Coxos)',
    'Ericeira (Crazy Left)',
    'Ericeira (Pedra Branca)',
    'Ericeira (Reef)',
    'Ericeira (Ribeira d\'Ilhas)',
    'Ericeira (Sao Lourenco)',
    'Foz do Lizandro',
    // Lisbon area
    'Adraga',
    'Carcavelos',
    'Costa da Caparica',
    'Guincho',
    'Praia Grande (Sintra)',
    'Santo Amaro de Oeiras',
    'São Pedro do Estoril',
    // Algarve
    'Amado',
    'Arrifana',
    'Beliche',
    'Bordeira',
    'Carrapateira',
    'Castelejo',
    'Cordoama',
    'Lagos (Meia Praia)',
    'Lagos (Porto de Mós)',
    'Monte Clerigo',
    'Sagres (Tonel)',
    'Zavial',
    // North
    'Cabedelo (Viana)',
    'Espinho',
    'Figueira da Foz (Buarcos)',
    'Figueira da Foz (Cabedelo)',
    'Matosinhos',
    'Moledo',
    'Santa Cruz',
    'Viana do Castelo',
    // Azores
    'Azores (Mosteiros)',
    'Azores (Rabo de Peixe)',
    'Azores (Santa Barbara)',
    // Madeira
    'Madeira (Jardim do Mar)',
    'Madeira (Paul do Mar)',
    'Madeira (Ponta Pequena)',
  ],
  'Spain': [
    // Basque Country
    'Bakio',
    'Barrika',
    'Laga',
    'Meñakoz',
    'Mundaka',
    'Orrua',
    'Punta Galea',
    'Sopela',
    'Sopelana (La Salvaje)',
    'Zarautz',
    // Cantabria
    'El Sardinero',
    'Langre',
    'Liencres',
    'Los Locos (Cantabria)',
    'Oyambre',
    'San Vicente de la Barquera',
    'Santa Marina',
    'Somo',
    // Asturias
    'Peñarronda',
    'Rodiles',
    'Salinas',
    'San Lorenzo',
    'Tapia de Casariego',
    'Verdicio',
    'Xagó',
    // Galicia
    'Baldaio',
    'Caión',
    'Furnas',
    'Pantin',
    'Patos',
    'Praia de Doninos',
    'Praia de Lanzada',
    'Razo',
    // Canary Islands – Lanzarote
    'Caleta de Caballo',
    'El Cotillo',
    'El Quemao',
    'Famara',
    'La Santa (Left & Right)',
    'Lobos',
    'Majanicho',
    'San Juan (Lanzarote)',
    // Canary Islands – Fuerteventura
    'North Shore (Fuerteventura)',
    'Playa de la Pared',
    'Rocky Point (Fuerteventura)',
    // Canary Islands – Gran Canaria
    'El Confital',
    'El Lloret',
    'La Barra (Gran Canaria)',
    'Maspalomas',
    // Canary Islands – Tenerife
    'Almaciga',
    'Benijo',
    'El Socorro',
    'Igueste de San Andrés',
    'Playa de las Américas',
    // Andalusia
    'Cádiz (La Cortadura)',
    'El Palmar',
    'Tarifa',
  ],
  'France': [
    // Landes / Hossegor
    'Biscarrosse',
    'Capbreton (La Piste)',
    'Capbreton (Le Santocha)',
    'Contis',
    'Hossegor (La Graviere)',
    'Hossegor (La Nord)',
    'Hossegor (La Sud)',
    'Hossegor (Les Culs Nus)',
    'Messanges',
    'Mimizan',
    'Moliets',
    'Seignosse (Le Penon)',
    'Seignosse (Les Bourdaines)',
    'Seignosse (Les Estagnots)',
    'Vieux-Boucau',
    // Gironde
    'Cap Ferret',
    'Lacanau',
    'Le Porge',
    'Montalivet',
    'Soulac',
    // Basque Coast
    'Anglet (La Barre)',
    'Anglet (Les Cavaliers)',
    'Anglet (Les Corsaires)',
    'Biarritz (Cote des Basques)',
    'Biarritz (Grande Plage)',
    'Biarritz (La Milady)',
    'Bidart',
    'Erromardie',
    'Guéthary (Cenitz)',
    'Guéthary (Parlementia)',
    'Hendaye',
    'Lafitenia',
    'Saint-Jean-de-Luz',
    // Brittany
    'Crozon (various)',
    'Guidel',
    'La Palue (Crozon)',
    'La Torche',
    'Penhors',
    'Quiberon',
    // Charente / Vendée
    'Bud Bud',
    'Ile d\'Oléron (various)',
    'Ile de Re (various)',
    'Les Sables-d\'Olonne',
    // Corsica
    'Corsica (Algajola)',
    'Corsica (Capo di Feno)',
  ],
  'Ireland': [
    // Donegal
    'Bundoran (The Peak)',
    'Magheroarty',
    'Mullaghmore',
    'Rossnowlagh',
    'Tullan Strand',
    // Sligo / Mayo
    'Achill Island',
    'Easkey Left',
    'Easkey Right',
    'Enniscrone',
    'Strandhill',
    // Clare
    'Crab Island',
    'Doolin Point',
    'Fanore',
    'Lahinch',
    'Spanish Point',
    // Kerry
    'Ballybunion',
    'Banna Strand',
    'Brandon Bay',
    'Inch Reef',
    // Cork / Waterford
    'Garretstown',
    'Inchydoney',
    'Tramore',
    // Northern Ireland
    'Benone',
    'Portrush (East Strand)',
    'Portrush (West Strand)',
    'Whiterocks',
  ],
  'United Kingdom': [
    // Cornwall
    'Bude (Crooklets)',
    'Bude (Summerleaze)',
    'Constantine Bay',
    'Harlyn Bay',
    'Mawgan Porth',
    'Crantock (Newquay)',
    'Fistral (Newquay)',
    'Great Western (Newquay)',
    'Lusty Glaze (Newquay)',
    'Tolcarne (Newquay)',
    'Towan (Newquay)',
    'Watergate Bay (Newquay)',
    'Whipsiderry (Newquay)',
    'Perranporth',
    'Polzeath',
    'Porthleven',
    'Porthmeor (St Ives)',
    'Porthtowan',
    'Praa Sands',
    'Sennen',
    'Widemouth Bay',
    // Devon
    'Bantham',
    'Croyde',
    'Lynmouth',
    'Saunton',
    'Woolacombe',
    // Inland wave pool (England)
    'The Wave',
    // Pembrokeshire
    'Freshwater West',
    'Manorbier',
    'Newgale',
    'Whitesands Bay',
    // Gower
    'Caswell Bay',
    'Langland Bay',
    'Llangennith (Rhossili)',
    // Scotland
    'Lost Shore',
    'Lewis (Dalmore)',
    'Machrihanish',
    'Pease Bay',
    'Sandside Bay',
    'Thurso (Brims Ness)',
    'Thurso East',
    'Tiree',
    // Yorkshire / Northeast
    'Saltburn',
    'Scarborough (Cayton Bay)',
    'Tynemouth (Longsands)',
  ],
  'Italy': [
    'Banzai (Lido di Ostia)',
    'Levanto',
    'Recco',
    'Santa Marinella',
    'Sardinia (Buggerru)',
    'Sardinia (Capo Mannu)',
    'Sardinia (Funtanamare)',
    'Sardinia (Porto Ferro)',
    'Varazze',
  ],
  'Norway': [
    'Borestranda (Jæren)',
    'Ervik',
    'Flakstad',
    'Hellestø (Jæren)',
    'Hoddevik',
    'Sola Beach',
    'Unstad (Lofoten)',
  ],
  'Iceland': [
    'Sandvik',
    'Thorli (Reykjanes)',
    'Vík í Mýrdal',
  ],
  'South Africa': [
    // Eastern Cape – J-Bay
    'Cape St Francis',
    'Gonubie',
    'Jeffreys Bay (Albatross)',
    'Jeffreys Bay (Boneyards)',
    'Jeffreys Bay (Kitchen Windows)',
    'Jeffreys Bay (Magna Tubes)',
    'Jeffreys Bay (Point)',
    'Jeffreys Bay (Seal Point)',
    'Jeffreys Bay (Supertubes)',
    'Nahoon Corner',
    'Nahoon Reef',
    // KwaZulu-Natal
    'Ballito',
    'Cave Rock',
    'Durban (Anstey\'s Beach)',
    'Durban (Dairy Beach)',
    'Durban (New Pier)',
    'Durban (North Beach)',
    'Durban (Snake Park)',
    'Durban (The Wedge)',
    'Salt Rock',
    'Scottburgh',
    'Umhlanga',
    // Western Cape
    'Big Bay',
    'Dungeons',
    'Llandudno',
    'Long Beach (Kommetjie)',
    'Melkbosstrand',
    'Misty Cliffs',
    'Muizenberg (Surfers Corner)',
    'Scarborough (Cape Town)',
    'Yzerfontein',
    // South Cape
    'Die Dam (Strand)',
    'Elands Bay',
    'Hermanus (Grotto Beach)',
    'Hermanus (Kammabaai)',
    'Mossel Bay (Inner Pool)',
    'Mossel Bay (Outer Pool)',
    'Still Bay',
    'Victoria Bay',
  ],
  'Morocco': [
    // Taghazout area
    'Banana Point',
    'Boilers',
    'Dracula\'s',
    'Hash Point',
    'Killer Point',
    'La Source',
    'Mysteries',
    'Panoramas',
    'Taghazout (Anchor Point)',
    'Tamri',
    // Imsouane
    'Imsouane (Cathedral)',
    'Imsouane (The Bay)',
    // South of Agadir
    'Agadir (beachbreaks)',
    'Anza',
    'Devil\'s Rock',
    'Sidi Ifni',
    'Tifnit',
    // Safi / Essaouira
    'Essaouira (Moulay Bouzerktoun)',
    'Essaouira (Sidi Kaouki)',
    'Safi',
    'Safi (Garden)',
    // North – Rabat / Casablanca
    'Bouznika',
    'Casablanca (Dar Bouazza)',
    'Casablanca (Jack Beach)',
    'Mehdia',
    'Moulay Bousselham',
    'Oued Cherrat',
    'Rabat (Nations)',
    'Rabat (Oudayas)',
    // Far North
    'Asilah (various)',
    'Tangier (various)',
    // Central
    'Oualidia',
  ],
  'Namibia': [
    'Donkey Bay',
    'Long Beach (Swakopmund)',
    'Lüderitz',
    'Skeleton Bay',
  ],
  'Senegal': [
    'Ngor Left',
    'Ngor Right',
    'Ouakam',
    'Secret Spot (Dakar)',
    'Vivier',
    'Yoff Beach',
  ],
  'India': [
    'Goa (Arambol)',
    'Goa (Ashwem)',
    'Gokarna',
    'Kovalam (Kerala)',
    'Kovelong (Covelong)',
    'Little Andaman (Butler Bay)',
    'Mahabalipuram',
    'Mangalore (Panambur)',
    'Mulki',
    'Puducherry (Serenity Beach)',
    'Varkala',
    'Visakhapatnam (Rushikonda)',
  ],
  'Barbados': [
    'Bathsheba',
    'Brandons',
    'Drill Hall',
    'Duppies',
    'Freights Bay',
    'Maycocks',
    'Parlours',
    'Soup Bowl',
    'South Point (Barbados)',
    'Tropicana (Barbados)',
  ],
  'Dominican Republic': [
    'Barahona (La Cienaga)',
    'Cabarete (Encuentro)',
    'Cabarete (Kite Beach)',
    'Cabarete (La Boca)',
    'El Broke',
    'La Boya',
    'Playa Grande (Rio San Juan)',
    'Punta Rucia',
    'Samana (Playa Coson)',
    'Sosua',
  ],
  'Argentina': [
    'Mar del Plata (Biologia)',
    'Mar del Plata (La Perla)',
    'Mar del Plata (Playa Grande)',
    'Miramar (Argentina)',
    'Necochea',
    'Pinamar',
    'Quequen',
    'Rada Tilly',
    'Santa Clara del Mar',
    'Villa Gesell',
  ],
  'Uruguay': [
    'Jose Ignacio',
    'La Paloma (La Aguada)',
    'La Paloma (La Balconada)',
    'La Pedrera',
    'Manantiales (Bikini)',
    'Montoya',
    'Punta del Diablo (La Viuda)',
    'Punta del Este (Brava)',
    'Punta del Este (La Barra)',
    'Santa Teresa (Uruguay)',
  ],
  'Colombia': [
    'Bahia Solano',
    'Cabo de la Vela',
    'Cartagena (La Boquilla)',
    'El Valle (Choco)',
    'Nuqui (Pico de Loro)',
    'Nuqui (Termales)',
    'Puerto Colombia',
    'Punta Roca (Barranquilla)',
    'San Andres (Punta Sur)',
    'Santa Marta (Los Naranjos)',
  ],
  'Guatemala': [
    'Champerico',
    'El Paredon',
    'Hawaii (Guatemala)',
    'Iztapa',
    'Las Lisas',
    'Monterrico',
    'Puerto San Jose',
    'Sipacate',
    'Tilapa',
    'Tulate',
  ],
  'Mozambique': [
    'Barra (Inhambane)',
    'Bilene',
    'Ponta do Ouro',
    'Ponta Malongane',
    'Ponta Mamoli',
    'Tofinho',
    'Tofo',
    'Vilanculos',
    'Xai-Xai',
    'Zavora',
  ],
  'Mauritius': [
    'Bel Ombre (Mauritius)',
    'Chameau',
    'Le Morne',
    'Manawa',
    'One Eye',
    'Poste Lafayette',
    'Riviere des Galets (Mauritius)',
    'Roches Noires (Mauritius)',
    'Souillac (Gris Gris)',
    'Tamarin Bay',
  ],
  'Reunion': [
    'Boucan Canot',
    'Cap Homard',
    'Etang Sale',
    'La Tortue (Reunion)',
    'Petite Ile',
    'Pointe au Sel',
    'Roches Noires (Reunion)',
    'Saint Leu',
    'Saint Pierre (Reunion)',
    'Trois Bassins',
  ],
  'Israel': [
    'Ashdod',
    'Ashkelon',
    'Bat Yam',
    'Caesarea (Aqueduct)',
    'Haifa (Backdoor)',
    'Herzliya',
    'Nahariya',
    'Netanya (Poleg)',
    'Tel Aviv (Dolphinarium)',
    'Tel Aviv (Hilton)',
  ],
  'Thailand': [
    'Khao Lak (Memories)',
    'Khao Lak (Pakarang)',
    'Koh Lanta (Klong Dao)',
    'Koh Phayam (Aow Yai)',
    'Phuket (Kalim)',
    'Phuket (Kamala)',
    'Phuket (Kata)',
    'Phuket (Nai Harn)',
    'Phuket (Surin)',
    'Songkhla',
  ],

  // ── SOUTH PACIFIC ────────────────────────────────────────
  'Papua New Guinea': [
    'Tupira (Lae)',
    'Vanimo',
  ],
};

/** Flat list of all spots (for backward-compat checks like includes()) */
export const SPOTS: readonly string[] = Object.values(SPOTS_BY_COUNTRY).flat();

export const COUNTRIES = Object.keys(SPOTS_BY_COUNTRY).sort((a, b) =>
  a.localeCompare(b, undefined, { sensitivity: 'base' })
);

/** Given a spot name, return the country it belongs to (or empty string). */
export function getCountryForSpot(spot: string): string {
  // Backward-compat for older logs that used "Newquay (Spot)" naming.
  const legacyNewquayMatch = spot.match(/^Newquay \((.+)\)$/);
  const canonicalSpot = legacyNewquayMatch ? `${legacyNewquayMatch[1]} (Newquay)` : spot;

  for (const [country, spots] of Object.entries(SPOTS_BY_COUNTRY)) {
    if (spots.includes(canonicalSpot)) return country;
  }
  return '';
}

export const TIDES = ['Low', 'Mid', 'High', 'Rising', 'Falling'] as const;

export const BOARD_TYPES = [
  { value: 'Longboard',   label: 'Long',  icon: '🏄' },
  { value: 'Mid-length',  label: 'Mid',   icon: '🛹' },
  { value: 'Fish',        label: 'Fish',  icon: '🐟' },
  { value: 'Shortboard',  label: 'Short', icon: '⚡' },
] as const;

export const LS_KEY = 'surfJournalEntries_v1';
export const LS_PROFILE_KEY = 'surfJournalProfile_v1';

export const SURFER_EMOJIS = [
  { image: '/surfers/surfer-1.png', label: 'Blue shirt surfer' },
  { image: '/surfers/surfer-2.png', label: 'Pink cap surfer' },
  { image: '/surfers/surfer-3.png', label: 'Colorful outfit surfer' },
  { image: '/surfers/surfer-4.png', label: 'Sunglasses surfer' },
  { image: '/surfers/surfer-5.png', label: 'Hawaiian shirt surfer' },
  { image: '/surfers/surfer-6.png', label: 'Board overhead surfer' },
  { image: '/surfers/surfer-7.png', label: 'Yellow board surfer' },
  { image: '/surfers/surfer-8.png', label: 'Pink outfit surfer' },
] as const;
