export const SPOTS_BY_COUNTRY: Record<string, readonly string[]> = {
  'Sri Lanka': [
    'Arugam Bay (Main Point)',
    'Arugam Bay (Baby Point)',
    'Peanut Farm',
    'Whiskey Point',
    'Pottuvil Point',
    'Okanda',
    'Elephant Rock',
    'Panama (Rights)',
    'The Wedge',
    'Hiriketiya',
    'Dickwella',
    'Matara',
    'Mirissa',
    'Weligama Bay',
    'Midigama',
    'Ahangama',
    'Kabalana',
    'Unawatuna',
    'Dalawella',
    'Galle (Reefs)',
    'Hikkaduwa',
    'Hikkaduwa (North Jetty)',
    'Hikkaduwa (Rivermouth)',
    'Mount Lavinia',
    'Nilaveli',
  ],
  'Indonesia': [
    'Uluwatu',
    'Padang Padang',
    'Bingin',
    'Impossibles',
    'Balangan',
    'Dreamland',
    'Suluban / Blue Point',
    'Nyang Nyang',
    'Green Bowl',
    'Nusa Dua',
    'Serangan',
    'Sanur Reef',
    'Kuta Reef',
    'Airport Lefts',
    'Airport Rights',
    'Halfway',
    'Canggu (Echo Beach)',
    'Canggu (Berawa)',
    'Canggu (Batu Bolong)',
    'Pererenan',
    'Keramas',
    'Medewi',
    'Balian',
    'Lembongan (Playgrounds)',
    'Lembongan (Shipwrecks)',
    'Lembongan (Lacerations)',
    'Nusa Penida',
    'Desert Point',
    'Gerupuk (Inside)',
    'Gerupuk (Outside)',
    'Ekas',
    'Kuta Lombok',
    'Supersuck (Sumbawa)',
    'Lakey Peak',
    'Periscopes',
    'Scar Reef',
    'Nias (Lagundri Bay / Sorake)',
    'Mentawais (Lance\'s Right)',
    'Mentawais (Lance\'s Left)',
    'Mentawais (Macaronis)',
    'Mentawais (Rifles)',
    'Mentawais (Bankvaults)',
    'Mentawais (HT\'s)',
    'Mentawais (Telescopes)',
    'Mentawais (Greenbush)',
    'Mentawais (Thunders)',
    'Panaitan (One Palm Point)',
  ],
  'Australia': [
    'Snapper Rocks',
    'Kirra',
    'Duranbah',
    'Burleigh Heads',
    'Greenmount',
    'Noosa (First Point)',
    'Sunshine Beach',
    'Currumbin Alley',
    'Byron Bay (The Pass)',
    'Lennox Head',
    'Broken Head',
    'Angourie',
    'Yamba',
    'Crescent Head',
    'Newcastle (Merewether)',
    'Bondi',
    'Manly',
    'Curl Curl',
    'Narrabeen',
    'Maroubra',
    'Cronulla (The Point)',
    'Jervis Bay (various)',
    'Ulladulla (various)',
    'Bermagui (various)',
    'Narooma (various)',
    'Torquay (Cosy Corner)',
    'Bells Beach',
    'Winkipop',
    'Jan Juc',
    'Point Addis',
    'Ocean Grove',
    '13th Beach',
    'Lorne',
    'Johanna',
    'Phillip Island (Woolamai)',
    'Margaret River (Main Break)',
    'The Box',
    'North Point',
    'Yallingup',
    'Trigg',
    'Scarborough',
    'Rottnest Island (various)',
    'Cactus Beach',
    'Middleton',
    'Waitpinga',
    'Parsons Beach',
    'Shipstern Bluff',
  ],
  'United States': [
    'Pipeline',
    'Backdoor',
    'Sunset Beach (Oahu)',
    'Waimea Bay',
    'Haleiwa (Alii Beach Park)',
    'Rocky Point',
    'Chun\'s Reef',
    'Makaha',
    'Ala Moana Bowls',
    'Diamond Head',
    'Sandy Beach',
    'Honolua Bay',
    'Ho\'okipa',
    'Hanalei Bay',
    'Tunnels',
    'Malibu (First Point)',
    'Zuma',
    'County Line',
    'Rincon',
    'Ventura Point',
    'Steamer Lane',
    'Pleasure Point',
    'Ocean Beach (San Francisco)',
    'Linda Mar (Pacifica)',
    'Mavericks',
    'Trestles (Upper)',
    'Trestles (Lowers)',
    'San Onofre',
    'Black\'s Beach',
    'Scripps',
    'Windansea',
    'Swami\'s',
    'Cardiff Reef',
    'Imperial Beach',
    'Huntington Pier',
    'Newport Wedge',
    'Salt Creek',
    'Montauk',
    'Rockaway',
    'Manasquan Inlet',
    'Sebastian Inlet',
    'New Smyrna Beach',
    'Cocoa Beach',
    'Rincon (Puerto Rico)',
    'Domes (Puerto Rico)',
    'Tres Palmas (Puerto Rico)',
  ],
  'Portugal': [
    'Supertubos (Peniche)',
    'Baleal',
    'Consolacao',
    'Lagide',
    'Almagreira',
    'Nazare (Praia do Norte)',
    'Sao Martinho do Porto',
    'Ericeira (Ribeira d\'Ilhas)',
    'Ericeira (Coxos)',
    'Ericeira (Pedra Branca)',
    'Ericeira (Sao Lourenco)',
    'Foz do Lizandro',
    'Carcavelos',
    'Guincho',
    'Costa da Caparica',
    'Praia Grande (Sintra)',
    'Adraga',
    'Arrifana',
    'Amado',
    'Monte Clerigo',
    'Zavial',
    'Sagres (Tonel)',
    'Beliche',
    'Figueira da Foz (Cabedelo)',
    'Espinho',
    'Matosinhos',
    'Moledo',
  ],
  'France': [
    'Hossegor (La Graviere)',
    'Hossegor (La Nord)',
    'Seignosse (Les Estagnots)',
    'Seignosse (Le Penon)',
    'Capbreton (Le Santocha)',
    'Capbreton (La Piste)',
    'Vieux-Boucau',
    'Moliets',
    'Biscarrosse',
    'Lacanau',
    'Soulac',
    'Biarritz (Cote des Basques)',
    'Biarritz (Grande Plage)',
    'Anglet (Les Cavaliers)',
    'Anglet (La Barre)',
    'Bidart',
    'Guéthary (Parlementia)',
    'Hendaye',
    'Saint-Jean-de-Luz',
    'La Torche',
    'Quiberon',
    'Ile de Re (various)',
    'Cap Ferret',
    'Crozon (various)',
  ],
  'South Africa': [
    'Jeffreys Bay (Supertubes)',
    'Jeffreys Bay (Point)',
    'Jeffreys Bay (Kitchen Windows)',
    'Jeffreys Bay (Seal Point)',
    'Cape St Francis',
    'Nahoon Reef',
    'Nahoon Corner',
    'Gonubie',
    'Durban (New Pier)',
    'Durban (North Beach)',
    'Durban (Dairy Beach)',
    'Cave Rock',
    'Scottburgh',
    'Ballito',
    'Muizenberg (Surfers Corner)',
    'Long Beach (Kommetjie)',
    'Scarborough',
    'Misty Cliffs',
    'Dungeons',
    'Llandudno',
    'Big Bay',
    'Elands Bay',
    'Victoria Bay',
    'Mossel Bay (various)',
    'Still Bay',
    'Hermanus (various)',
  ],
  'Brazil': [
    'Saquarema (Itauna)',
    'Arpoador',
    'Barra da Tijuca',
    'Copacabana (corners)',
    'Prainha (Rio)',
    'Grumari',
    'Buzios (various)',
    'Florianopolis (Praia Mole)',
    'Florianopolis (Joaquina)',
    'Florianopolis (Campeche)',
    'Florianopolis (Santinho)',
    'Guarda do Embau',
    'Imbituba',
    'Garopaba',
    'Ferrugem',
    'Maresias',
    'Itamambuca',
    'Camburi',
    'Santos (various)',
    'Guaruja (Praia do Tombo)',
    'Praia Brava (Itajai)',
    'Fernando de Noronha (Cacimba do Padre)',
    'Itacare',
  ],
  'Costa Rica': [
    'Tamarindo',
    'Playa Grande',
    'Langosta',
    'Avellanas (Little Hawaii)',
    'Playa Negra',
    'Junquillal',
    'Marbella',
    'Nosara (Guiones)',
    'Ostional',
    'Samara',
    'Santa Teresa',
    'Mal Pais',
    'Jaco',
    'Playa Hermosa (Central)',
    'Boca Barranca',
    'Esterillos',
    'Bejuco',
    'Dominical',
    'Dominicalito',
    'Matapalo',
    'Pavones',
    'Puerto Viejo',
    'Salsa Brava',
  ],
  'Mexico': [
    'Todos Santos',
    'Cerritos',
    'San Pedrito',
    'Cabo San Lucas (Monuments)',
    'Zippers',
    'Costa Azul',
    'Shipwrecks',
    'Scorpion Bay (San Juanico)',
    'Punta Abreojos',
    'Punta San Carlos',
    'San Miguel (Ensenada)',
    'K-38 / Salsipuedes corridor',
    'Puerto Escondido (Zicatela)',
    'La Punta (Puerto Escondido)',
    'Barra de la Cruz',
    'Salina Cruz points (various)',
    'Sayulita',
    'Punta de Mita',
    'La Lancha',
    'San Pancho',
    'Manzanillo',
    'Pascuales',
    'Troncones',
    'La Saladita',
  ],
  'Morocco': [
    'Taghazout (Anchor Point)',
    'Killer Point',
    'Boilers',
    'Banana Point',
    'Hash Point',
    'Panoramas',
    'Dracula\'s',
    'Mysteries',
    'La Source',
    'Tamri',
    'Imsouane (The Bay)',
    'Imsouane (Cathedral)',
    'Devil\'s Rock',
    'Anza',
    'Agadir (beachbreaks)',
    'Safi',
    'Essaouira (various)',
    'Rabat (various)',
    'Casablanca (Dar Bouazza)',
    'Bouznika',
    'Oued Cherrat',
    'Asilah (various)',
    'Tangier (various)',
  ],
};

/** Flat list of all spots (for backward-compat checks like includes()) */
export const SPOTS: readonly string[] = Object.values(SPOTS_BY_COUNTRY).flat();

export const COUNTRIES = Object.keys(SPOTS_BY_COUNTRY);

/** Given a spot name, return the country it belongs to (or empty string). */
export function getCountryForSpot(spot: string): string {
  for (const [country, spots] of Object.entries(SPOTS_BY_COUNTRY)) {
    if (spots.includes(spot)) return country;
  }
  return '';
}

export const TIDES = ['Low', 'Mid', 'High', 'Rising', 'Falling'] as const;

export const BOARD_TYPES = [
  { value: 'Longboard',   label: 'Long',  icon: '🏄' },
  { value: 'Mid-length',  label: 'Mid',   icon: '🛹' },
  { value: 'Fish',        label: 'Fish',  icon: '🐟' },
  { value: 'Shortboard',  label: 'Short', icon: '⚡' },
] as const;

export const LS_KEY = 'surfJournalEntries_v1';
export const LS_PROFILE_KEY = 'surfJournalProfile_v1';

export const SURFER_EMOJIS = [
  { emoji: '🏄‍♂️', label: 'Yellow man' },
  { emoji: '🏄‍♀️', label: 'Yellow woman' },
  { emoji: '🏄🏻‍♂️', label: 'White man' },
  { emoji: '🏄🏻‍♀️', label: 'White woman' },
  { emoji: '🏄🏽‍♂️', label: 'Brown man' },
  { emoji: '🏄🏽‍♀️', label: 'Brown woman' },
  { emoji: '🏄🏿‍♂️', label: 'Black man' },
  { emoji: '🏄🏿‍♀️', label: 'Black woman' },
] as const;
