export const SPOTS_BY_COUNTRY: Record<string, readonly string[]> = {
  // ── ASIA ─────────────────────────────────────────────────
  'Sri Lanka': [
    // East coast – Arugam Bay area
    'Arugam Bay (Main Point)',
    'Arugam Bay (Baby Point)',
    'Peanut Farm',
    'Whiskey Point',
    'Pottuvil Point',
    'Okanda',
    'Elephant Rock',
    'Panama (Rights)',
    'The Wedge',
    'Crocodile Rock',
    'Lighthouse (A-Bay)',
    'Pottuvil Lagoon Mouth',
    // South coast
    'Hiriketiya',
    'Dickwella',
    'Talalla',
    'Matara',
    'Mirissa',
    'Weligama Bay',
    'Midigama (Lazy Left)',
    'Midigama (Lazy Right)',
    'Midigama',
    'Ahangama',
    'Kabalana',
    'The Rock (Ahangama)',
    'Unawatuna',
    'Dalawella',
    'Galle (Reefs)',
    // Southwest coast
    'Hikkaduwa',
    'Hikkaduwa (North Jetty)',
    'Hikkaduwa (Rivermouth)',
    'Hikkaduwa (Main Reef)',
    'Bentota',
    'Mount Lavinia',
    // East / North
    'Nilaveli',
    'Arugam Bay (Mudu)',
  ],
  'Indonesia': [
    // Bali – Bukit Peninsula
    'Uluwatu',
    'Padang Padang',
    'Bingin',
    'Impossibles',
    'Balangan',
    'Dreamland',
    'Suluban / Blue Point',
    'Nyang Nyang',
    'Green Bowl',
    // Bali – South
    'Nusa Dua',
    'Serangan',
    'Sanur Reef',
    'Kuta Reef',
    'Kuta Beach',
    'Airport Lefts',
    'Airport Rights',
    'Halfway',
    // Bali – Canggu / West
    'Canggu (Echo Beach)',
    'Canggu (Berawa)',
    'Canggu (Batu Bolong)',
    'Canggu (Old Man\'s)',
    'Pererenan',
    'Seseh',
    'Tanah Lot',
    // Bali – East
    'Keramas',
    'Ketewel',
    'Hyatt Reef',
    // Bali – West & North
    'Medewi',
    'Balian',
    'Cekik (Secret Spot)',
    // Nusa Islands
    'Lembongan (Playgrounds)',
    'Lembongan (Shipwrecks)',
    'Lembongan (Lacerations)',
    'Lembongan (Razors)',
    'Ceningan (The Cliff)',
    'Nusa Penida',
    // Lombok
    'Desert Point',
    'Gerupuk (Inside)',
    'Gerupuk (Outside)',
    'Gerupuk (Don Don)',
    'Ekas',
    'Kuta Lombok',
    'Mawi',
    'Selong Belanak',
    'Senggigi',
    'Tanjung Aan',
    // Sumbawa
    'Supersuck (Sumbawa)',
    'Lakey Peak',
    'Lakey Pipe',
    'Periscopes',
    'Scar Reef',
    'Yo-Yo\'s',
    // Sumba
    'Nihiwatu (God\'s Left)',
    'Tarimbang',
    // Java
    'G-Land (Grajagan)',
    'Cimaja',
    'Batu Karas',
    'Pacitan (various)',
    'Panaitan (One Palm Point)',
    'Ombak Tujuh (Seven Waves)',
    // Sumatra
    'Nias (Lagundri Bay / Sorake)',
    'Nias (The Point)',
    'Tanjung Setia (Krui)',
    'Krui (The Peak)',
    'Krui (Mandiri)',
    'Krui (Way Jambu)',
    // Mentawais
    'Mentawais (Lance\'s Right)',
    'Mentawais (Lance\'s Left)',
    'Mentawais (Macaronis)',
    'Mentawais (Rifles)',
    'Mentawais (Bankvaults)',
    'Mentawais (HT\'s)',
    'Mentawais (Telescopes)',
    'Mentawais (Greenbush)',
    'Mentawais (Thunders)',
    'Mentawais (Kandui Left)',
    'Mentawais (Beng Bengs)',
    'Mentawais (Nipussi)',
    'Mentawais (Pitstops)',
    'Mentawais (E-Bay)',
    // Aceh
    'Aceh (Lhoknga)',
  ],
  'Japan': [
    // Chiba
    'Ichinomiya (Shidashita)',
    'Taito Beach',
    'Chiba (Maruki)',
    'Katsuura',
    'Onjuku',
    // Shonan
    'Shonan (Kugenuma)',
    'Shonan (Chigasaki)',
    'Shonan (Fujisawa)',
    'Enoshima',
    // Shikoku
    'Ikumi',
    'Kaifu (Shikoku)',
    'Nahari',
    // Miyazaki
    'Kisakihama',
    'Aoshima',
    'Kizaki-hama',
    // Islands
    'Niijima',
    'Tanegashima',
    'Yakushima',
    // Others
    'Isonoura',
    'Shirahama (Wakayama)',
  ],
  'Philippines': [
    // Siargao
    'Cloud 9',
    'Tuason Point',
    'Rock Island',
    'Stimpy\'s',
    'Jacking Horse',
    'Daku Reef',
    'Pacifico (Siargao)',
    'Quicksilver',
    // La Union
    'San Juan (La Union)',
    'Urbiztondo',
    'Monaliza Point',
    // Baler (Aurora)
    'Sabang Beach (Baler)',
    'Charlie\'s Point',
    'Cemento Reef',
    'Lindy\'s Point',
    // Catanduanes
    'Majestics (Catanduanes)',
    'Puraran',
    // Zambales
    'San Narciso',
    'San Felipe',
    'Crystal Beach (Zambales)',
    // Others
    'Lanuza (Surigao)',
    'Dahican (Mati)',
    'Pagudpud',
    'Bagasbas (Camarines Norte)',
  ],
  'Maldives': [
    // North Male Atoll
    'Chickens',
    'Cokes',
    'Lohis',
    'Ninjas',
    'Sultans',
    'Honky\'s',
    'Jailbreaks',
    'Pasta Point',
    'Tucky Joe\'s',
    // South Male Atoll
    'Riptides',
    'Quarters',
    'Native',
    'Guru\'s',
    'Last Stop',
    // Central Atolls
    'Malik\'s',
    'Twin Peaks (Meemu Atoll)',
    'Veyvah Point',
    // Outer Atolls
    'Five Islands (Laamu)',
    'Yin Yang (Laamu)',
    'Refugees',
  ],
  'Taiwan': [
    'Jinzun Harbor',
    'Jialeshuei',
    'Nanwan',
    'Dulan',
    'Wai-Ao',
    'Baishawan',
    'Zhongjiao Bay',
  ],

  // ── OCEANIA ──────────────────────────────────────────────
  'Australia': [
    // Queensland – Gold Coast
    'Snapper Rocks',
    'Kirra',
    'Duranbah',
    'Burleigh Heads',
    'Greenmount',
    'Currumbin Alley',
    'Palm Beach Reef',
    'The Spit',
    // Queensland – Sunshine Coast / North
    'Noosa (First Point)',
    'Noosa (Nationals)',
    'Noosa (Tea Tree)',
    'Sunshine Beach',
    'Alex Headland',
    'Mooloolaba',
    'Caloundra (Kings Beach)',
    'North Stradbroke Island',
    // NSW – North Coast
    'Byron Bay (The Pass)',
    'Byron Bay (The Wreck)',
    'Byron Bay (Tallows)',
    'Lennox Head',
    'Broken Head',
    'Angourie',
    'Yamba',
    'Coffs Harbour (Park Beach)',
    'Crescent Head',
    'South West Rocks',
    // NSW – Central Coast / Hunter
    'Newcastle (Merewether)',
    'Newcastle (Bar Beach)',
    'Newcastle (Nobbys)',
    'Avoca Beach',
    'North Narrabeen',
    'Dee Why',
    'Freshwater',
    // NSW – Sydney
    'Bondi',
    'Manly',
    'Curl Curl',
    'Narrabeen',
    'Maroubra',
    'Cronulla (The Point)',
    // NSW – South Coast
    'Jervis Bay (various)',
    'Ulladulla (various)',
    'Bermagui (various)',
    'Narooma (various)',
    'Merimbula',
    // Victoria – Great Ocean Road
    'Torquay (Cosy Corner)',
    'Bells Beach',
    'Winkipop',
    'Jan Juc',
    'Point Addis',
    'Ocean Grove',
    '13th Beach',
    'Lorne',
    'Johanna',
    'Phillip Island (Woolamai)',
    'Gunnamatta',
    'Portsea (Back Beach)',
    // Western Australia – Margaret River
    'Margaret River (Main Break)',
    'Margaret River (Surfers Point)',
    'The Box',
    'North Point',
    'Yallingup',
    'Gracetown',
    'Prevelly',
    'Lefthanders',
    'Gnaraloo',
    'Red Bluff',
    // Western Australia – Perth
    'Trigg',
    'Scarborough',
    'Cottesloe',
    'Rottnest Island (Strickland Bay)',
    'Rottnest Island (Stark Bay)',
    // South Australia
    'Cactus Beach',
    'Middleton',
    'Waitpinga',
    'Parsons Beach',
    'Pennington Bay (Kangaroo Island)',
    'Pondalowie Bay',
    // Tasmania
    'Shipstern Bluff',
    'Eaglehawk Neck',
    'Clifton Beach (Tas)',
    'Marrawah',
  ],
  'New Zealand': [
    // Waikato / Bay of Plenty
    'Raglan (Manu Bay)',
    'Raglan (Indicators)',
    'Raglan (Whale Bay)',
    'Mount Maunganui',
    'Papamoa',
    // Auckland
    'Piha',
    'Muriwai',
    'Bethells Beach',
    // Northland
    'Shipwreck Bay',
    'Ahipara',
    'Mangawhai Heads',
    // East Cape
    'Gisborne (Wainui)',
    'Gisborne (Makorori)',
    'Mahia',
    // Taranaki
    'Stent Road',
    'Kumara Patch',
    'Fitzroy Beach',
    // Wellington / Wairarapa
    'Lyall Bay',
    'Castlepoint',
    'Riversdale',
    // South Island
    'Taylors Mistake',
    'Sumner',
    'Kaikoura',
    'St Clair (Dunedin)',
    'Papatowai',
    'Porpoise Bay (Curio Bay)',
    'Punakaiki',
    'Tauranga Bay (Westport)',
  ],
  'Fiji': [
    'Cloudbreak',
    'Restaurants',
    'Frigates',
    'Swimming Pools',
    'Desperations',
    'Wilkes Pass',
    'Namotu Lefts',
    'Tavarua Rights',
    'Lighthouse (Kadavu)',
    'King Kong Left',
    'Natadola',
    'Sigatoka Rivermouth',
  ],
  'Tahiti / French Polynesia': [
    'Teahupo\'o',
    'Papara',
    'Papenoo',
    'Sapinus',
    'Taapuna',
    'Maraa',
    'Vairao',
  ],

  // ── AMERICAS ─────────────────────────────────────────────
  'United States': [
    // Hawaii – Oahu
    'Pipeline',
    'Backdoor',
    'Sunset Beach (Oahu)',
    'Waimea Bay',
    'Haleiwa (Alii Beach Park)',
    'Rocky Point',
    'Chun\'s Reef',
    'Laniakea',
    'Velzyland',
    'Makaha',
    'Ala Moana Bowls',
    'Kaiser\'s',
    'Diamond Head',
    'Sandy Beach',
    // Hawaii – Maui
    'Honolua Bay',
    'Ho\'okipa',
    'Peahi (Jaws)',
    'Lahaina Harbor',
    'Lanes (Maui)',
    // Hawaii – Kauai
    'Hanalei Bay',
    'Tunnels',
    'Polihale',
    'Pakala Village (Infinities)',
    // Hawaii – Big Island
    'Pine Trees (Big Island)',
    'Banyans (Big Island)',
    'Honoli\'i',
    // California – Southern
    'Malibu (First Point)',
    'Malibu (Second Point)',
    'Malibu (Third Point)',
    'Topanga',
    'Zuma',
    'County Line',
    'El Porto',
    'Hermosa Beach',
    'Manhattan Beach (El Porto)',
    'Rincon',
    'Ventura Point',
    'C Street (Ventura)',
    'Silver Strand',
    'Emma Wood',
    'Trestles (Upper)',
    'Trestles (Lowers)',
    'Trestles (Cottons)',
    'San Onofre',
    'T-Street (San Clemente)',
    'Church (San Clemente)',
    'Black\'s Beach',
    'Scripps',
    'Windansea',
    'Tourmaline',
    'La Jolla Shores',
    'Swami\'s',
    'Cardiff Reef',
    'Imperial Beach',
    'Huntington Pier',
    'Bolsa Chica',
    'Newport Wedge',
    'Newport Point',
    'Salt Creek',
    'Dana Point',
    'Doheny',
    'San Clemente Pier',
    '54th Street (Newport)',
    // California – Central
    'Steamer Lane',
    'Pleasure Point',
    'Mitchell\'s Cove',
    'Moss Landing',
    'Marina State Beach',
    'Pacific Grove',
    'Pismo Beach',
    'Jalama',
    'Refugio',
    // California – NorCal
    'Ocean Beach (San Francisco)',
    'Linda Mar (Pacifica)',
    'Mavericks',
    'Bolinas',
    'Stinson Beach',
    // East Coast
    'Montauk',
    'Ditch Plains',
    'Rockaway',
    'Long Beach (NY)',
    'Manasquan Inlet',
    'Belmar',
    'Asbury Park',
    'Cape Hatteras (Outer Banks)',
    'Wrightsville Beach',
    'Folly Beach',
    // Florida
    'Sebastian Inlet',
    'New Smyrna Beach',
    'Cocoa Beach',
    'Ponce Inlet',
    'Jacksonville Beach',
    'St. Augustine',
    'Reef Road (Palm Beach)',
    // Puerto Rico
    'Rincon (Puerto Rico)',
    'Domes (Puerto Rico)',
    'Tres Palmas (Puerto Rico)',
    'Maria\'s (Puerto Rico)',
    'Sandy Beach (Puerto Rico)',
    'Wilderness (Puerto Rico)',
    'Gas Chambers (Puerto Rico)',
    'Surfer\'s Beach (Aguadilla)',
    // Great Lakes / Texas
    'Galveston (TX)',
    'South Padre Island',
  ],
  'Canada': [
    // British Columbia
    'Tofino (Cox Bay)',
    'Tofino (Long Beach)',
    'Tofino (Chestermans)',
    'Tofino (Wickaninnish)',
    'Jordan River',
    'Sombrio Beach',
    // Nova Scotia
    'Lawrencetown',
    'Cow Bay',
    'Martinique Beach',
    'Lawrencetown Point',
  ],
  'Mexico': [
    // Baja California Sur
    'Todos Santos',
    'Cerritos',
    'San Pedrito',
    'Cabo San Lucas (Monuments)',
    'Zippers',
    'Costa Azul',
    'Shipwrecks',
    'El Tule',
    'Nine Palms',
    // Baja California
    'Scorpion Bay (San Juanico)',
    'Punta Abreojos',
    'Punta San Carlos',
    'San Miguel (Ensenada)',
    'K-38 / Salsipuedes corridor',
    'K-55',
    'Isla Todos Santos (Big Wave)',
    // Oaxaca
    'Puerto Escondido (Zicatela)',
    'La Punta (Puerto Escondido)',
    'Carrizalillo',
    'Barra de la Cruz',
    'Salina Cruz points (various)',
    'Chacahua',
    'Zipolite',
    // Nayarit / Riviera Nayarit
    'Sayulita',
    'Punta de Mita',
    'La Lancha',
    'San Pancho',
    'Burros',
    'Lo de Marcos',
    // Jalisco
    'Boca de Pascuales',
    // Colima / Michoacan / Guerrero
    'Manzanillo',
    'Pascuales',
    'Troncones',
    'La Saladita',
    'Nexpa',
    'Ixtapa (Escolleras)',
    'Playa Linda (Ixtapa)',
    'Petacalco',
  ],
  'Costa Rica': [
    // Guanacaste (North Pacific)
    'Tamarindo',
    'Playa Grande',
    'Langosta',
    'Avellanas (Little Hawaii)',
    'Playa Negra',
    'Junquillal',
    'Marbella',
    'Witch\'s Rock',
    'Ollie\'s Point',
    // Nicoya Peninsula
    'Nosara (Guiones)',
    'Ostional',
    'Samara',
    'Camaronal',
    'Santa Teresa',
    'Mal Pais',
    'Playa Carmen',
    'Playa Hermosa (Santa Teresa)',
    'Manzanillo (Nicoya)',
    // Central Pacific
    'Jaco',
    'Playa Hermosa (Central)',
    'Boca Barranca',
    'Esterillos',
    'Bejuco',
    'Playa Escondida',
    // South Pacific
    'Dominical',
    'Dominicalito',
    'Uvita',
    'Matapalo',
    'Pavones',
    // Caribbean
    'Puerto Viejo',
    'Salsa Brava',
    'Cocles',
    'Playa Bonita',
  ],
  'Nicaragua': [
    // Rivas / Tola
    'Popoyo',
    'Playa Colorado',
    'Playa Santana',
    'Manzanillo (Nicaragua)',
    'Panga Drops',
    'Playgrounds (Nicaragua)',
    'Lance\'s Left (Nicaragua)',
    // San Juan del Sur area
    'Playa Maderas',
    'Playa Marsella',
    'Playa Hermosa (Nicaragua)',
    'Playa Remanso',
    'Playa Yankee',
    'San Juan del Sur (beachbreak)',
    // North
    'Astillero',
    'Poneloya',
    'Las Peñitas',
    'Aposentillo',
  ],
  'El Salvador': [
    // La Libertad
    'Punta Roca',
    'El Tunco',
    'El Sunzal',
    'El Zonte',
    'La Bocana',
    'Conchalio',
    'San Blas',
    'K-59 (El Salvador)',
    // East
    'Las Flores',
    'Punta Mango',
    'El Cuco',
    'Mizata',
    // West
    'Los Cobanos',
  ],
  'Panama': [
    'Santa Catalina',
    'Playa Venao',
    'Cambutal',
    'Playa Morrillo',
    'Bocas del Toro (Paunch)',
    'Bocas del Toro (Dumpers)',
    'Bocas del Toro (Bluff Beach)',
    'Bocas del Toro (Silverbacks)',
    'Red Frog Beach',
    'Playa Teta',
    'Coronado',
  ],
  'Peru': [
    // North
    'Chicama',
    'Lobitos',
    'Máncora',
    'Cabo Blanco',
    'Pacasmayo',
    'Huanchaco',
    'Órganos',
    // Lima Area
    'Punta Hermosa',
    'Punta Rocas',
    'Pico Alto',
    'Señoritas',
    'Caballeros',
    'La Herradura',
    'San Bartolo',
    'Cerro Azul',
    'Makaha (Peru)',
    'Kon Tiki',
    'Playa Waikiki (Lima)',
    // South
    'Arica (Peru side)',
  ],
  'Chile': [
    // Norte Grande
    'Arica (El Gringo)',
    'Arica (El Buey)',
    'Arica (La Isla)',
    'Iquique (Punta Cavancha)',
    'Iquique (Huayquique)',
    // Central
    'Pichilemu (Punta de Lobos)',
    'Pichilemu (La Puntilla)',
    'Pichilemu (Infiernillo)',
    'Matanzas',
    'Topocalma',
    'Constitución',
    'Renaca',
    'Reñaca',
    'Ritoque',
    'Viña del Mar',
    'Con-Con (Playa Negra)',
    // South
    'Buchupureo',
    'Cobquecura',
    'Pelluhue',
    'Puertecillo',
    'Lebu',
  ],
  'Ecuador': [
    'Montañita',
    'Canoa',
    'Ayampe',
    'Olón',
    'San Mateo',
    'Mompiche',
    'Engabao',
    'Playa de los Frailes',
    'Santa Marianita',
    'Same',
    'Galápagos (Tortuga Bay)',
  ],
  'Brazil': [
    // Rio de Janeiro
    'Saquarema (Itauna)',
    'Arpoador',
    'Barra da Tijuca',
    'Copacabana (corners)',
    'Prainha (Rio)',
    'Grumari',
    'Buzios (various)',
    // Santa Catarina
    'Florianopolis (Praia Mole)',
    'Florianopolis (Joaquina)',
    'Florianopolis (Campeche)',
    'Florianopolis (Santinho)',
    'Florianopolis (Barra da Lagoa)',
    'Guarda do Embau',
    'Imbituba',
    'Imbituba (Praia da Vila)',
    'Garopaba',
    'Ferrugem',
    'Praia do Rosa',
    'Praia Brava (Itajai)',
    'Torres',
    // São Paulo
    'Maresias',
    'Itamambuca',
    'Camburi',
    'Santos (various)',
    'Guaruja (Praia do Tombo)',
    'Ubatuba (Praia Grande)',
    'Ubatuba (Praia Vermelha)',
    // Northeast
    'Fernando de Noronha (Cacimba do Padre)',
    'Fernando de Noronha (Boldró)',
    'Itacare',
    'Stella Maris (Salvador)',
    'Maracaipe',
    'Porto de Galinhas',
    'Praia da Pipa',
    'São Conrado (Rio)',
    // South
    'Torres (RS)',
    'Farol de Santa Marta',
  ],

  // ── EUROPE ───────────────────────────────────────────────
  'Portugal': [
    // Peniche area
    'Supertubos (Peniche)',
    'Baleal',
    'Consolacao',
    'Lagide',
    'Almagreira',
    'Molho Leste',
    'Cantinho da Baía',
    // Nazaré
    'Nazare (Praia do Norte)',
    'Nazare (Praia da Vila)',
    'Sao Martinho do Porto',
    // Ericeira (World Surfing Reserve)
    'Ericeira (Ribeira d\'Ilhas)',
    'Ericeira (Coxos)',
    'Ericeira (Pedra Branca)',
    'Ericeira (Sao Lourenco)',
    'Ericeira (Reef)',
    'Ericeira (Crazy Left)',
    'Ericeira (Cave)',
    'Foz do Lizandro',
    // Lisbon area
    'Carcavelos',
    'Guincho',
    'Costa da Caparica',
    'Praia Grande (Sintra)',
    'Adraga',
    'Santo Amaro de Oeiras',
    'São Pedro do Estoril',
    // Algarve
    'Arrifana',
    'Amado',
    'Monte Clerigo',
    'Zavial',
    'Sagres (Tonel)',
    'Beliche',
    'Bordeira',
    'Castelejo',
    'Cordoama',
    'Carrapateira',
    'Lagos (Meia Praia)',
    'Lagos (Porto de Mós)',
    // North
    'Figueira da Foz (Cabedelo)',
    'Figueira da Foz (Buarcos)',
    'Espinho',
    'Matosinhos',
    'Moledo',
    'Viana do Castelo',
    'Cabedelo (Viana)',
    'Santa Cruz',
    // Azores
    'Azores (Santa Barbara)',
    'Azores (Rabo de Peixe)',
    'Azores (Mosteiros)',
    // Madeira
    'Madeira (Jardim do Mar)',
    'Madeira (Paul do Mar)',
    'Madeira (Ponta Pequena)',
  ],
  'Spain': [
    // Basque Country
    'Mundaka',
    'Meñakoz',
    'Sopelana (La Salvaje)',
    'Bakio',
    'Zarautz',
    'Sopela',
    'Barrika',
    'Orrua',
    'Punta Galea',
    'Laga',
    // Cantabria
    'Somo',
    'Liencres',
    'Los Locos (Cantabria)',
    'Santa Marina',
    'Langre',
    'El Sardinero',
    'Oyambre',
    'San Vicente de la Barquera',
    // Asturias
    'Rodiles',
    'Salinas',
    'San Lorenzo',
    'Tapia de Casariego',
    'Verdicio',
    'Xagó',
    'Peñarronda',
    // Galicia
    'Pantin',
    'Razo',
    'Caión',
    'Baldaio',
    'Patos',
    'Furnas',
    'Praia de Lanzada',
    'Praia de Doninos',
    // Canary Islands – Lanzarote
    'El Quemao',
    'La Santa (Left & Right)',
    'Famara',
    'San Juan (Lanzarote)',
    'Lobos',
    'Majanicho',
    'El Cotillo',
    'Caleta de Caballo',
    // Canary Islands – Fuerteventura
    'North Shore (Fuerteventura)',
    'Playa de la Pared',
    'Rocky Point (Fuerteventura)',
    // Canary Islands – Gran Canaria
    'El Confital',
    'El Lloret',
    'La Barra (Gran Canaria)',
    'Maspalomas',
    // Canary Islands – Tenerife
    'El Socorro',
    'Playa de las Américas',
    'Igueste de San Andrés',
    'Almaciga',
    'Benijo',
    // Andalusia
    'El Palmar',
    'Tarifa',
    'Cádiz (La Cortadura)',
  ],
  'France': [
    // Landes / Hossegor
    'Hossegor (La Graviere)',
    'Hossegor (La Nord)',
    'Hossegor (La Sud)',
    'Hossegor (Les Culs Nus)',
    'Seignosse (Les Estagnots)',
    'Seignosse (Le Penon)',
    'Seignosse (Les Bourdaines)',
    'Capbreton (Le Santocha)',
    'Capbreton (La Piste)',
    'Vieux-Boucau',
    'Moliets',
    'Mimizan',
    'Biscarrosse',
    'Messanges',
    'Contis',
    // Gironde
    'Lacanau',
    'Soulac',
    'Cap Ferret',
    'Le Porge',
    'Montalivet',
    // Basque Coast
    'Biarritz (Cote des Basques)',
    'Biarritz (Grande Plage)',
    'Biarritz (La Milady)',
    'Anglet (Les Cavaliers)',
    'Anglet (La Barre)',
    'Anglet (Les Corsaires)',
    'Bidart',
    'Guéthary (Parlementia)',
    'Guéthary (Cenitz)',
    'Hendaye',
    'Saint-Jean-de-Luz',
    'Lafitenia',
    'Erromardie',
    // Brittany
    'La Torche',
    'Quiberon',
    'Crozon (various)',
    'Penhors',
    'Guidel',
    'La Palue (Crozon)',
    // Charente / Vendée
    'Ile de Re (various)',
    'Ile d\'Oléron (various)',
    'Les Sables-d\'Olonne',
    'Bud Bud',
    // Corsica
    'Corsica (Capo di Feno)',
    'Corsica (Algajola)',
  ],
  'Ireland': [
    // Donegal
    'Bundoran (The Peak)',
    'Tullan Strand',
    'Rossnowlagh',
    'Mullaghmore',
    'Magheroarty',
    // Sligo / Mayo
    'Easkey Left',
    'Easkey Right',
    'Strandhill',
    'Enniscrone',
    'Achill Island',
    // Clare
    'Lahinch',
    'Crab Island',
    'Doolin Point',
    'Spanish Point',
    'Fanore',
    // Kerry
    'Inch Reef',
    'Ballybunion',
    'Brandon Bay',
    'Banna Strand',
    // Cork / Waterford
    'Inchydoney',
    'Garretstown',
    'Tramore',
    // Northern Ireland
    'Portrush (East Strand)',
    'Portrush (West Strand)',
    'Whiterocks',
    'Benone',
  ],
  'United Kingdom': [
    // Cornwall
    'Newquay (Fistral)',
    'Newquay (Watergate Bay)',
    'Newquay (Crantock)',
    'Newquay (Towan)',
    'Newquay (Great Western)',
    'Newquay (Tolcarne)',
    'Newquay (Whipsiderry)',
    'Mawgan Porth',
    'Sennen',
    'Porthtowan',
    'Perranporth',
    'Polzeath',
    'Bude (Crooklets)',
    'Bude (Summerleaze)',
    'Widemouth Bay',
    'Harlyn Bay',
    'Constantine Bay',
    'Praa Sands',
    'Porthleven',
    // Devon
    'Croyde',
    'Woolacombe',
    'Saunton',
    'Bantham',
    'Lynmouth',
    // Pembrokeshire
    'Freshwater West',
    'Manorbier',
    'Newgale',
    'Whitesands Bay',
    // Gower
    'Llangennith (Rhossili)',
    'Langland Bay',
    'Caswell Bay',
    // Scotland
    'Thurso East',
    'Thurso (Brims Ness)',
    'Sandside Bay',
    'Pease Bay',
    'Machrihanish',
    'Lewis (Dalmore)',
    'Tiree',
    // Yorkshire / Northeast
    'Scarborough (Cayton Bay)',
    'Saltburn',
    'Tynemouth (Longsands)',
  ],
  'Italy': [
    'Levanto',
    'Varazze',
    'Recco',
    'Sardinia (Capo Mannu)',
    'Sardinia (Funtanamare)',
    'Sardinia (Buggerru)',
    'Sardinia (Porto Ferro)',
    'Santa Marinella',
    'Banzai (Lido di Ostia)',
  ],
  'Norway': [
    'Unstad (Lofoten)',
    'Flakstad',
    'Hoddevik',
    'Ervik',
    'Borestranda (Jæren)',
    'Hellestø (Jæren)',
    'Sola Beach',
  ],
  'Iceland': [
    'Thorli (Reykjanes)',
    'Sandvik',
    'Vík í Mýrdal',
  ],
  'South Africa': [
    // Eastern Cape – J-Bay
    'Jeffreys Bay (Supertubes)',
    'Jeffreys Bay (Point)',
    'Jeffreys Bay (Kitchen Windows)',
    'Jeffreys Bay (Seal Point)',
    'Jeffreys Bay (Albatross)',
    'Jeffreys Bay (Magna Tubes)',
    'Jeffreys Bay (Boneyards)',
    'Cape St Francis',
    'Nahoon Reef',
    'Nahoon Corner',
    'Gonubie',
    // KwaZulu-Natal
    'Durban (New Pier)',
    'Durban (North Beach)',
    'Durban (Dairy Beach)',
    'Durban (Anstey\'s Beach)',
    'Cave Rock',
    'Scottburgh',
    'Ballito',
    'Salt Rock',
    'Umhlanga',
    'Durban (The Wedge)',
    'Durban (Snake Park)',
    // Western Cape
    'Muizenberg (Surfers Corner)',
    'Long Beach (Kommetjie)',
    'Scarborough (Cape Town)',
    'Misty Cliffs',
    'Dungeons',
    'Llandudno',
    'Big Bay',
    'Yzerfontein',
    'Melkbosstrand',
    // South Cape
    'Elands Bay',
    'Victoria Bay',
    'Mossel Bay (Inner Pool)',
    'Mossel Bay (Outer Pool)',
    'Still Bay',
    'Hermanus (Grotto Beach)',
    'Hermanus (Kammabaai)',
    'Die Dam (Strand)',
  ],
  'Morocco': [
    // Taghazout area
    'Taghazout (Anchor Point)',
    'Killer Point',
    'Boilers',
    'Banana Point',
    'Hash Point',
    'Panoramas',
    'Dracula\'s',
    'Mysteries',
    'La Source',
    'Tamri',
    // Imsouane
    'Imsouane (The Bay)',
    'Imsouane (Cathedral)',
    // South of Agadir
    'Devil\'s Rock',
    'Anza',
    'Agadir (beachbreaks)',
    'Tifnit',
    'Sidi Ifni',
    // Safi / Essaouira
    'Safi',
    'Safi (Garden)',
    'Essaouira (Moulay Bouzerktoun)',
    'Essaouira (Sidi Kaouki)',
    // North – Rabat / Casablanca
    'Rabat (Oudayas)',
    'Rabat (Nations)',
    'Casablanca (Dar Bouazza)',
    'Casablanca (Jack Beach)',
    'Bouznika',
    'Oued Cherrat',
    'Mehdia',
    'Moulay Bousselham',
    // Far North
    'Asilah (various)',
    'Tangier (various)',
    // Central
    'Oualidia',
  ],
  'Namibia': [
    'Skeleton Bay',
    'Lüderitz',
    'Long Beach (Swakopmund)',
    'Donkey Bay',
  ],
  'Senegal': [
    'Ngor Right',
    'Ngor Left',
    'Ouakam',
    'Vivier',
    'Yoff Beach',
    'Secret Spot (Dakar)',
  ],
  'India': [
    'Kovalam (Kerala)',
    'Varkala',
    'Mulki',
    'Mangalore (Panambur)',
    'Gokarna',
    'Goa (Ashwem)',
    'Goa (Arambol)',
    'Mahabalipuram',
    'Kovelong (Covelong)',
    'Puducherry (Serenity Beach)',
    'Visakhapatnam (Rushikonda)',
    'Little Andaman (Butler Bay)',
  ],
  'Barbados': [
    'Soup Bowl',
    'Parlours',
    'Bathsheba',
    'Duppies',
    'Tropicana (Barbados)',
    'South Point (Barbados)',
    'Freights Bay',
    'Brandons',
    'Maycocks',
    'Drill Hall',
  ],
  'Dominican Republic': [
    'Cabarete (Encuentro)',
    'Cabarete (Kite Beach)',
    'Cabarete (La Boca)',
    'Playa Grande (Rio San Juan)',
    'Sosua',
    'El Broke',
    'La Boya',
    'Barahona (La Cienaga)',
    'Samana (Playa Coson)',
    'Punta Rucia',
  ],
  'Argentina': [
    'Mar del Plata (Playa Grande)',
    'Mar del Plata (La Perla)',
    'Mar del Plata (Biologia)',
    'Miramar (Argentina)',
    'Necochea',
    'Quequen',
    'Pinamar',
    'Villa Gesell',
    'Santa Clara del Mar',
    'Rada Tilly',
  ],
  'Uruguay': [
    'La Paloma (La Aguada)',
    'La Paloma (La Balconada)',
    'Punta del Diablo (La Viuda)',
    'Santa Teresa (Uruguay)',
    'La Pedrera',
    'Jose Ignacio',
    'Punta del Este (La Barra)',
    'Punta del Este (Brava)',
    'Montoya',
    'Manantiales (Bikini)',
  ],
  'Colombia': [
    'Nuqui (Termales)',
    'Nuqui (Pico de Loro)',
    'El Valle (Choco)',
    'Bahia Solano',
    'Punta Roca (Barranquilla)',
    'Puerto Colombia',
    'Santa Marta (Los Naranjos)',
    'Cartagena (La Boquilla)',
    'San Andres (Punta Sur)',
    'Cabo de la Vela',
  ],
  'Guatemala': [
    'El Paredon',
    'Iztapa',
    'Puerto San Jose',
    'Sipacate',
    'Monterrico',
    'Champerico',
    'Tilapa',
    'Tulate',
    'Las Lisas',
    'Hawaii (Guatemala)',
  ],
  'Mozambique': [
    'Tofo',
    'Tofinho',
    'Barra (Inhambane)',
    'Zavora',
    'Ponta do Ouro',
    'Ponta Malongane',
    'Ponta Mamoli',
    'Bilene',
    'Xai-Xai',
    'Vilanculos',
  ],
  'Mauritius': [
    'Tamarin Bay',
    'One Eye',
    'Manawa',
    'Chameau',
    'Le Morne',
    'Bel Ombre (Mauritius)',
    'Souillac (Gris Gris)',
    'Riviere des Galets (Mauritius)',
    'Poste Lafayette',
    'Roches Noires (Mauritius)',
  ],
  'Reunion': [
    'Saint Leu',
    'Trois Bassins',
    'Boucan Canot',
    'Roches Noires (Reunion)',
    'Etang Sale',
    'Pointe au Sel',
    'La Tortue (Reunion)',
    'Saint Pierre (Reunion)',
    'Cap Homard',
    'Petite Ile',
  ],
  'Israel': [
    'Herzliya',
    'Tel Aviv (Hilton)',
    'Tel Aviv (Dolphinarium)',
    'Bat Yam',
    'Ashdod',
    'Ashkelon',
    'Netanya (Poleg)',
    'Haifa (Backdoor)',
    'Nahariya',
    'Caesarea (Aqueduct)',
  ],
  'Thailand': [
    'Phuket (Kata)',
    'Phuket (Kalim)',
    'Phuket (Nai Harn)',
    'Phuket (Kamala)',
    'Phuket (Surin)',
    'Khao Lak (Pakarang)',
    'Khao Lak (Memories)',
    'Koh Phayam (Aow Yai)',
    'Koh Lanta (Klong Dao)',
    'Songkhla',
  ],

  // ── SOUTH PACIFIC ────────────────────────────────────────
  'Papua New Guinea': [
    'Tupira (Lae)',
    'Vanimo',
  ],
};

/** Flat list of all spots (for backward-compat checks like includes()) */
export const SPOTS: readonly string[] = Object.values(SPOTS_BY_COUNTRY).flat();

export const COUNTRIES = Object.keys(SPOTS_BY_COUNTRY);

/** Given a spot name, return the country it belongs to (or empty string). */
export function getCountryForSpot(spot: string): string {
  for (const [country, spots] of Object.entries(SPOTS_BY_COUNTRY)) {
    if (spots.includes(spot)) return country;
  }
  return '';
}

export const TIDES = ['Low', 'Mid', 'High', 'Rising', 'Falling'] as const;

export const BOARD_TYPES = [
  { value: 'Longboard',   label: 'Long',  icon: '🏄' },
  { value: 'Mid-length',  label: 'Mid',   icon: '🛹' },
  { value: 'Fish',        label: 'Fish',  icon: '🐟' },
  { value: 'Shortboard',  label: 'Short', icon: '⚡' },
] as const;

export const LS_KEY = 'surfJournalEntries_v1';
export const LS_PROFILE_KEY = 'surfJournalProfile_v1';

export const SURFER_EMOJIS = [
  { image: '/surfers/surfer-1.png', label: 'Blue shirt surfer' },
  { image: '/surfers/surfer-2.png', label: 'Pink cap surfer' },
  { image: '/surfers/surfer-3.png', label: 'Colorful outfit surfer' },
  { image: '/surfers/surfer-4.png', label: 'Sunglasses surfer' },
  { image: '/surfers/surfer-5.png', label: 'Hawaiian shirt surfer' },
  { image: '/surfers/surfer-6.png', label: 'Board overhead surfer' },
  { image: '/surfers/surfer-7.png', label: 'Yellow board surfer' },
  { image: '/surfers/surfer-8.png', label: 'Pink outfit surfer' },
] as const;
